name: Keepalive

on:
  schedule:
    - cron: '0 0 1 * *' # every 1st day of the month at 00:00(UTC)
  workflow_dispatch:
permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: keepalive
      - uses: ./.github/actions/configure-git
      - name: Create empty commit
        run: |
          git commit --allow-empty -m "chore: monthly keepalive $(date -u +%F) [skip ci]"
      - run: git push
