name: KeepAlive

on:
  schedule:
    - cron: '0 0 1 * *' # every 1st day of the month at 00:00(UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure Git name and email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Switch to keepalive branch (if not exists, create it)
        run: git switch keepalive 2>/dev/null || git switch -c keepalive
      - name: Create empty commit
        run: git commit --allow-empty -m "monthly keepalive $(date -u +%F) [skip ci]"
      - run: git push origin keepalive
