name: tmptest

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days at midnight
  workflow_dispatch:

jobs:
  tmptest:
    runs-on: ubuntu-slim
    steps:
      # Setup Homebrew (Homebrew isn't installed in ubuntu-slim)
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - uses: Homebrew/actions/setup-homebrew@main
      # Test
      - run: brew tap --force homebrew/core
      - name: Test
        run: |
          brew livecheck --quiet --json bat