name: Bump Formula and Cask

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days at midnight
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-slim
    steps:
      - name: echo env
        run: |
          echo GITHUB_TOKEN=$GITHUB_TOKEN
      - name: echo env2
        run: |
          echo GH_TOKEN=$GH_TOKEN