name: Update Homebrew Formula

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days at midnight
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Also "Allow GitHub Actions to create and approve pull requests" is required on the repository settings
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # In GitHub Actions, 'brew bump-formula-pr' requires HOMEBREW_GITHUB_API_TOKEN
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git name and email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: Homebrew/actions/setup-homebrew@main
      - run: brew tap horaguy/extras
      - name: Bump all formulas
        run: |
          shopt -s nullglob # To prevent error when no formula files are found
          for formula_file in Formula/*.rb; do
            echo "Bumping $formula_file"
            formula=$(basename "$formula_file" .rb)
            .github/scripts/bump-pr.sh "$formula"
          done
