name: Update Homebrew Cask

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days at midnight
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      # Also "Allow GitHub Actions to create and approve pull requests" is required on the repository settings
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # In GitHub Actions, 'brew bump-cask-pr' requires HOMEBREW_GITHUB_API_TOKEN
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git name and email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - run: brew tap horaguy/extras
      - name: Bump all casks
        run: |
          shopt -s nullglob # To prevent error when no cask files are found
          for cask_file in Casks/*.rb; do
            echo "Bumping $cask_file"
            cask=$(basename "$cask_file" .rb)
            .github/scripts/bump-pr.sh "$cask" --cask
          done
