name: Update Homebrew Formula

on:
  schedule:
    - cron: '0 0 */3 * *' # every 3 days at midnight
  workflow_dispatch:

jobs:
  update-formula:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Also "Allow GitHub Actions to create and approve pull requests" is required on the repository settings
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # In GitHub Actions, 'brew bump-formula-pr' requires HOMEBREW_GITHUB_API_TOKEN 
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - uses: ./.github/actions/configure-git
      - run: brew tap horaguy/extras
      - name: Bump regular formula
        run: |
          FORMULAS=(
            "codegpt"
            "picosakura"
            "sakuramml"
          )
          for formula in "${FORMULAS[@]}"; do
            .github/scripts/bump-formula.sh "$formula"
          done