name: Update Homebrew Cask

on:
  schedule:
    - cron: "0 0 */3 * *" # every 3 days at midnight
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Also "Allow GitHub Actions to create and approve pull requests" is required on the repository settings
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # In GitHub Actions, 'brew bump-cask-pr' requires HOMEBREW_GITHUB_API_TOKEN
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - uses: ./.github/actions/configure-git
      - run: brew tap horaguy/extras
      - name: Bump all casks
        run: |
          for cask_file in Casks/*.rb; do
            cask=$(basename "$cask_file" .rb)
            echo "Bumping $cask"
            .github/scripts/bump-cask.sh "$cask"
          done
